language: python
matrix:
  include:
    - python: 2.7
      dist: xenial
      sudo: false
    - python: 3.4
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest==3.6.3
script:
  - py.test pybloom_live
